//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(OjVolunteer.Model.OjVolunteerEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets42a576f6268fbc65f53054ec9c3ec9dced7ed13b22370c32c47cceef9708fcb1))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySets42a576f6268fbc65f53054ec9c3ec9dced7ed13b22370c32c47cceef9708fcb1 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "42a576f6268fbc65f53054ec9c3ec9dced7ed13b22370c32c47cceef9708fcb1"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "OjVolunteerModelStoreContainer.Activity")
            {
                return GetView0();
            }

            if (extentName == "OjVolunteerModelStoreContainer.ActivityDetail")
            {
                return GetView1();
            }

            if (extentName == "OjVolunteerModelStoreContainer.ActivityType")
            {
                return GetView2();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Favors")
            {
                return GetView3();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Integrals")
            {
                return GetView4();
            }

            if (extentName == "OjVolunteerModelStoreContainer.OrganizeInfo")
            {
                return GetView5();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Talks")
            {
                return GetView6();
            }

            if (extentName == "OjVolunteerModelStoreContainer.UserDuration")
            {
                return GetView7();
            }

            if (extentName == "OjVolunteerModelStoreContainer.UserEnroll")
            {
                return GetView8();
            }

            if (extentName == "OjVolunteerModelStoreContainer.UserInfo")
            {
                return GetView9();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Badge")
            {
                return GetView10();
            }

            if (extentName == "OjVolunteerModelStoreContainer.UserBadge")
            {
                return GetView11();
            }

            if (extentName == "OjVolunteerEntities.Activity")
            {
                return GetView12();
            }

            if (extentName == "OjVolunteerEntities.ActivityDetail")
            {
                return GetView13();
            }

            if (extentName == "OjVolunteerEntities.ActivityType")
            {
                return GetView14();
            }

            if (extentName == "OjVolunteerEntities.Favors")
            {
                return GetView15();
            }

            if (extentName == "OjVolunteerEntities.Integrals")
            {
                return GetView16();
            }

            if (extentName == "OjVolunteerEntities.OrganizeInfo")
            {
                return GetView17();
            }

            if (extentName == "OjVolunteerEntities.Talks")
            {
                return GetView18();
            }

            if (extentName == "OjVolunteerEntities.UserDuration")
            {
                return GetView19();
            }

            if (extentName == "OjVolunteerEntities.UserEnroll")
            {
                return GetView20();
            }

            if (extentName == "OjVolunteerEntities.UserInfo")
            {
                return GetView21();
            }

            if (extentName == "OjVolunteerEntities.Badge")
            {
                return GetView22();
            }

            if (extentName == "OjVolunteerEntities.UserBadge")
            {
                return GetView23();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Department")
            {
                return GetView24();
            }

            if (extentName == "OjVolunteerEntities.Department")
            {
                return GetView25();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Major")
            {
                return GetView26();
            }

            if (extentName == "OjVolunteerEntities.Major")
            {
                return GetView27();
            }

            if (extentName == "OjVolunteerModelStoreContainer.Political")
            {
                return GetView28();
            }

            if (extentName == "OjVolunteerEntities.Political")
            {
                return GetView29();
            }

            if (extentName == "OjVolunteerModelStoreContainer.v_User_ActDetail")
            {
                return GetView30();
            }

            if (extentName == "OjVolunteerEntities.v_User_ActDetail")
            {
                return GetView31();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Activity.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Activity
        [OjVolunteerModel.Store.Activity](T1.Activity_ActivityID, T1.Activity_ActivityName, T1.Activity_ActivityIcon, T1.Activity_ActivityTypeID, T1.Activity_ActivityAddress, T1.Activity_ActivityAddressX, T1.Activity_ActivityAddressY, T1.Activity_ActivityContent, T1.Activity_ActivityPrediNum, T1.Activity_ActivityManagerID, T1.Activity_ActivityApplyUserInfoID, T1.Activity_ActivityApplyOrganizeID, T1.Activity_ActivityClicks, T1.Activity_ActivityEnrollEnd, T1.Activity_ActivityEnrollStart, T1.Activity_ActivityStart, T1.Activity_ActivityEnd, T1.Activity_ActivityPolitical, T1.Activity_ActivityMajor, T1.Activity_ActivityDepartment, T1.Activity_CreateTime, T1.Activity_ModfiedOn, T1.Activity_Remark, T1.Activity_Status, T1.Activity_ActivityAddressDetail)
    FROM (
        SELECT 
            T.ActivityID AS Activity_ActivityID, 
            T.ActivityName AS Activity_ActivityName, 
            T.ActivityIcon AS Activity_ActivityIcon, 
            T.ActivityTypeID AS Activity_ActivityTypeID, 
            T.ActivityAddress AS Activity_ActivityAddress, 
            T.ActivityAddressX AS Activity_ActivityAddressX, 
            T.ActivityAddressY AS Activity_ActivityAddressY, 
            T.ActivityContent AS Activity_ActivityContent, 
            T.ActivityPrediNum AS Activity_ActivityPrediNum, 
            T.ActivityManagerID AS Activity_ActivityManagerID, 
            T.ActivityApplyUserInfoID AS Activity_ActivityApplyUserInfoID, 
            T.ActivityApplyOrganizeID AS Activity_ActivityApplyOrganizeID, 
            T.ActivityClicks AS Activity_ActivityClicks, 
            T.ActivityEnrollEnd AS Activity_ActivityEnrollEnd, 
            T.ActivityEnrollStart AS Activity_ActivityEnrollStart, 
            T.ActivityStart AS Activity_ActivityStart, 
            T.ActivityEnd AS Activity_ActivityEnd, 
            T.ActivityPolitical AS Activity_ActivityPolitical, 
            T.ActivityMajor AS Activity_ActivityMajor, 
            T.ActivityDepartment AS Activity_ActivityDepartment, 
            T.CreateTime AS Activity_CreateTime, 
            T.ModfiedOn AS Activity_ModfiedOn, 
            T.Remark AS Activity_Remark, 
            T.Status AS Activity_Status, 
            T.ActivityAddressDetail AS Activity_ActivityAddressDetail, 
            True AS _from0
        FROM OjVolunteerEntities.Activity AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.ActivityDetail.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ActivityDetail
        [OjVolunteerModel.Store.ActivityDetail](T1.ActivityDetail_ActivityDetailID, T1.ActivityDetail_UserInfoId, T1.ActivityDetail_ActivityID, T1.ActivityDetail_ActivityDetailTime, T1.ActivityDetail_CreateTime, T1.ActivityDetail_ModfiedOn, T1.ActivityDetail_Remark, T1.ActivityDetail_Status)
    FROM (
        SELECT 
            T.ActivityDetailID AS ActivityDetail_ActivityDetailID, 
            T.UserInfoId AS ActivityDetail_UserInfoId, 
            T.ActivityID AS ActivityDetail_ActivityID, 
            T.ActivityDetailTime AS ActivityDetail_ActivityDetailTime, 
            T.CreateTime AS ActivityDetail_CreateTime, 
            T.ModfiedOn AS ActivityDetail_ModfiedOn, 
            T.Remark AS ActivityDetail_Remark, 
            T.Status AS ActivityDetail_Status, 
            True AS _from0
        FROM OjVolunteerEntities.ActivityDetail AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.ActivityType.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ActivityType
        [OjVolunteerModel.Store.ActivityType](T1.ActivityType_ActivityTypeID, T1.ActivityType_ActivityTypeName, T1.ActivityType_CreateTime, T1.ActivityType_ModfiedOn, T1.ActivityType_Remark, T1.ActivityType_Status)
    FROM (
        SELECT 
            T.ActivityTypeID AS ActivityType_ActivityTypeID, 
            T.ActivityTypeName AS ActivityType_ActivityTypeName, 
            T.CreateTime AS ActivityType_CreateTime, 
            T.ModfiedOn AS ActivityType_ModfiedOn, 
            T.Remark AS ActivityType_Remark, 
            T.Status AS ActivityType_Status, 
            True AS _from0
        FROM OjVolunteerEntities.ActivityType AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Favors.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Favors
        [OjVolunteerModel.Store.Favors](T1.Favors_FavorID, T1.Favors_TalkID, T1.Favors_UserInfoID, T1.Favors_CreateTime, T1.Favors_ModfiedOn, T1.Favors_Remark, T1.Favors_Status)
    FROM (
        SELECT 
            T.FavorID AS Favors_FavorID, 
            T.TalkID AS Favors_TalkID, 
            T.UserInfoID AS Favors_UserInfoID, 
            T.CreateTime AS Favors_CreateTime, 
            T.ModfiedOn AS Favors_ModfiedOn, 
            T.Remark AS Favors_Remark, 
            T.Status AS Favors_Status, 
            True AS _from0
        FROM OjVolunteerEntities.Favors AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Integrals.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Integrals
        [OjVolunteerModel.Store.Integrals](T1.Integrals_IntegralID, T1.Integrals_UserInfoID, T1.Integrals_IntegralNum, T1.Integrals_IntegralIndex, T1.Integrals_CreateTime, T1.Integrals_ModfiedOn, T1.Integrals_Remark, T1.Integrals_Status)
    FROM (
        SELECT 
            T.IntegralID AS Integrals_IntegralID, 
            T.UserInfoID AS Integrals_UserInfoID, 
            T.IntegralNum AS Integrals_IntegralNum, 
            T.IntegralIndex AS Integrals_IntegralIndex, 
            T.CreateTime AS Integrals_CreateTime, 
            T.ModfiedOn AS Integrals_ModfiedOn, 
            T.Remark AS Integrals_Remark, 
            T.Status AS Integrals_Status, 
            True AS _from0
        FROM OjVolunteerEntities.Integrals AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.OrganizeInfo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrganizeInfo
        [OjVolunteerModel.Store.OrganizeInfo](T1.OrganizeInfo_OrganizeInfoID, T1.OrganizeInfo_OrganizeInfoLoginId, T1.OrganizeInfo_OrganizeInfoShowName, T1.OrganizeInfo_OrganizeInfoPwd, T1.OrganizeInfo_OrganizeInfoPeople, T1.OrganizeInfo_OrganizeInfoPhone, T1.OrganizeInfo_OrganizeInfoEmail, T1.OrganizeInfo_OrganizeInfoManageId, T1.OrganizeInfo_OrganizeInfoLastTime, T1.OrganizeInfo_CreateTime, T1.OrganizeInfo_ModfiedOn, T1.OrganizeInfo_Remark, T1.OrganizeInfo_Status, T1.OrganizeInfo_OrganizeInfoIcon, T1.OrganizeInfo_ActivityCount)
    FROM (
        SELECT 
            T.OrganizeInfoID AS OrganizeInfo_OrganizeInfoID, 
            T.OrganizeInfoLoginId AS OrganizeInfo_OrganizeInfoLoginId, 
            T.OrganizeInfoShowName AS OrganizeInfo_OrganizeInfoShowName, 
            T.OrganizeInfoPwd AS OrganizeInfo_OrganizeInfoPwd, 
            T.OrganizeInfoPeople AS OrganizeInfo_OrganizeInfoPeople, 
            T.OrganizeInfoPhone AS OrganizeInfo_OrganizeInfoPhone, 
            T.OrganizeInfoEmail AS OrganizeInfo_OrganizeInfoEmail, 
            T.OrganizeInfoManageId AS OrganizeInfo_OrganizeInfoManageId, 
            T.OrganizeInfoLastTime AS OrganizeInfo_OrganizeInfoLastTime, 
            T.CreateTime AS OrganizeInfo_CreateTime, 
            T.ModfiedOn AS OrganizeInfo_ModfiedOn, 
            T.Remark AS OrganizeInfo_Remark, 
            T.Status AS OrganizeInfo_Status, 
            T.OrganizeInfoIcon AS OrganizeInfo_OrganizeInfoIcon, 
            T.ActivityCount AS OrganizeInfo_ActivityCount, 
            True AS _from0
        FROM OjVolunteerEntities.OrganizeInfo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Talks.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Talks
        [OjVolunteerModel.Store.Talks](T1.Talks_TalkID, T1.Talks_UserInfoID, T1.Talks_TalkContent, T1.Talks_TalkFavorsNum, T1.Talks_CreateTime, T1.Talks_ModfiedOn, T1.Talks_Remark, T1.Talks_Status, T1.Talks_OrganizeInfoID, T1.Talks_TalkImagePath)
    FROM (
        SELECT 
            T.TalkID AS Talks_TalkID, 
            T.UserInfoID AS Talks_UserInfoID, 
            T.TalkContent AS Talks_TalkContent, 
            T.TalkFavorsNum AS Talks_TalkFavorsNum, 
            T.CreateTime AS Talks_CreateTime, 
            T.ModfiedOn AS Talks_ModfiedOn, 
            T.Remark AS Talks_Remark, 
            T.Status AS Talks_Status, 
            T.OrganizeInfoID AS Talks_OrganizeInfoID, 
            T.TalkImagePath AS Talks_TalkImagePath, 
            True AS _from0
        FROM OjVolunteerEntities.Talks AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.UserDuration.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserDuration
        [OjVolunteerModel.Store.UserDuration](T1.UserDuration_UserDurationID, T1.UserDuration_UserDurationTotal, T1.UserDuration_UserDurationPropartyTotal, T1.UserDuration_UserDurationPartyTotal, T1.UserDuration_UserDurationPropartyTime, T1.UserDuration_UserDurationPartyTime, T1.UserDuration_CreateTime, T1.UserDuration_ModfiedOn, T1.UserDuration_Remark, T1.UserDuration_Status, T1.UserDuration_UserDurationNormalTotal)
    FROM (
        SELECT 
            T.UserDurationID AS UserDuration_UserDurationID, 
            T.UserDurationTotal AS UserDuration_UserDurationTotal, 
            T.UserDurationPropartyTotal AS UserDuration_UserDurationPropartyTotal, 
            T.UserDurationPartyTotal AS UserDuration_UserDurationPartyTotal, 
            T.UserDurationPropartyTime AS UserDuration_UserDurationPropartyTime, 
            T.UserDurationPartyTime AS UserDuration_UserDurationPartyTime, 
            T.CreateTime AS UserDuration_CreateTime, 
            T.ModfiedOn AS UserDuration_ModfiedOn, 
            T.Remark AS UserDuration_Remark, 
            T.Status AS UserDuration_Status, 
            T.UserDurationNormalTotal AS UserDuration_UserDurationNormalTotal, 
            True AS _from0
        FROM OjVolunteerEntities.UserDuration AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.UserEnroll.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserEnroll
        [OjVolunteerModel.Store.UserEnroll](T1.UserEnroll_UserEnrollID, T1.UserEnroll_ActivityID, T1.UserEnroll_UserInfoID, T1.UserEnroll_UserEnrollStart, T1.UserEnroll_UserEnrollActivityStart, T1.UserEnroll_UserEnrollActivityEnd, T1.UserEnroll_CreateTime, T1.UserEnroll_ModfiedOn, T1.UserEnroll_Remark, T1.UserEnroll_Status, T1.UserEnroll_ActivityTime)
    FROM (
        SELECT 
            T.UserEnrollID AS UserEnroll_UserEnrollID, 
            T.ActivityID AS UserEnroll_ActivityID, 
            T.UserInfoID AS UserEnroll_UserInfoID, 
            T.UserEnrollStart AS UserEnroll_UserEnrollStart, 
            T.UserEnrollActivityStart AS UserEnroll_UserEnrollActivityStart, 
            T.UserEnrollActivityEnd AS UserEnroll_UserEnrollActivityEnd, 
            T.CreateTime AS UserEnroll_CreateTime, 
            T.ModfiedOn AS UserEnroll_ModfiedOn, 
            T.Remark AS UserEnroll_Remark, 
            T.Status AS UserEnroll_Status, 
            T.ActivityTime AS UserEnroll_ActivityTime, 
            True AS _from0
        FROM OjVolunteerEntities.UserEnroll AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.UserInfo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserInfo
        [OjVolunteerModel.Store.UserInfo](T1.UserInfo_UserInfoID, T1.UserInfo_UserInfoLoginId, T1.UserInfo_UserInfoPwd, T1.UserInfo_UserInfoStuId, T1.UserInfo_UserInfoShowName, T1.UserInfo_UserInfoPhone, T1.UserInfo_UserInfoEmail, T1.UserInfo_MajorID, T1.UserInfo_DepartmentID, T1.UserInfo_PoliticalID, T1.UserInfo_UpdatePoliticalID, T1.UserInfo_OrganizeInfoID, T1.UserInfo_UserInfoLastTime, T1.UserInfo_CreateTime, T1.UserInfo_ModfiedOn, T1.UserInfo_Remark, T1.UserInfo_Status, T1.UserInfo_UserInfoIcon, T1.UserInfo_UserInfoIDcard, T1.UserInfo_UserInfoTalkCount)
    FROM (
        SELECT 
            T.UserInfoID AS UserInfo_UserInfoID, 
            T.UserInfoLoginId AS UserInfo_UserInfoLoginId, 
            T.UserInfoPwd AS UserInfo_UserInfoPwd, 
            T.UserInfoStuId AS UserInfo_UserInfoStuId, 
            T.UserInfoShowName AS UserInfo_UserInfoShowName, 
            T.UserInfoPhone AS UserInfo_UserInfoPhone, 
            T.UserInfoEmail AS UserInfo_UserInfoEmail, 
            T.MajorID AS UserInfo_MajorID, 
            T.DepartmentID AS UserInfo_DepartmentID, 
            T.PoliticalID AS UserInfo_PoliticalID, 
            T.UpdatePoliticalID AS UserInfo_UpdatePoliticalID, 
            T.OrganizeInfoID AS UserInfo_OrganizeInfoID, 
            T.UserInfoLastTime AS UserInfo_UserInfoLastTime, 
            T.CreateTime AS UserInfo_CreateTime, 
            T.ModfiedOn AS UserInfo_ModfiedOn, 
            T.Remark AS UserInfo_Remark, 
            T.Status AS UserInfo_Status, 
            T.UserInfoIcon AS UserInfo_UserInfoIcon, 
            T.UserInfoIDcard AS UserInfo_UserInfoIDcard, 
            T.UserInfoTalkCount AS UserInfo_UserInfoTalkCount, 
            True AS _from0
        FROM OjVolunteerEntities.UserInfo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Badge.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Badge
        [OjVolunteerModel.Store.Badge](T1.Badge_BadgeID, T1.Badge_BadgeName, T1.Badge_Staus, T1.Badge_Remark, T1.Badge_CreateTime, T1.Badge_ImgSrc)
    FROM (
        SELECT 
            T.BadgeID AS Badge_BadgeID, 
            T.BadgeName AS Badge_BadgeName, 
            T.Staus AS Badge_Staus, 
            T.Remark AS Badge_Remark, 
            T.CreateTime AS Badge_CreateTime, 
            T.ImgSrc AS Badge_ImgSrc, 
            True AS _from0
        FROM OjVolunteerEntities.Badge AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.UserBadge.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserBadge
        [OjVolunteerModel.Store.UserBadge](T1.UserBadge_UserBadgeID, T1.UserBadge_UserInfoID, T1.UserBadge_BadgeID, T1.UserBadge_CreateTime, T1.UserBadge_Staus)
    FROM (
        SELECT 
            T.UserBadgeID AS UserBadge_UserBadgeID, 
            T.UserInfoID AS UserBadge_UserInfoID, 
            T.BadgeID AS UserBadge_BadgeID, 
            T.CreateTime AS UserBadge_CreateTime, 
            T.Staus AS UserBadge_Staus, 
            True AS _from0
        FROM OjVolunteerEntities.UserBadge AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Activity.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Activity
        [OjVolunteerModel.Activity](T1.Activity_ActivityID, T1.Activity_ActivityName, T1.Activity_ActivityIcon, T1.Activity_ActivityTypeID, T1.Activity_ActivityAddress, T1.Activity_ActivityAddressX, T1.Activity_ActivityAddressY, T1.Activity_ActivityContent, T1.Activity_ActivityPrediNum, T1.Activity_ActivityManagerID, T1.Activity_ActivityApplyUserInfoID, T1.Activity_ActivityApplyOrganizeID, T1.Activity_ActivityClicks, T1.Activity_ActivityEnrollEnd, T1.Activity_ActivityEnrollStart, T1.Activity_ActivityStart, T1.Activity_ActivityEnd, T1.Activity_ActivityPolitical, T1.Activity_ActivityMajor, T1.Activity_ActivityDepartment, T1.Activity_CreateTime, T1.Activity_ModfiedOn, T1.Activity_Remark, T1.Activity_Status, T1.Activity_ActivityAddressDetail)
    FROM (
        SELECT 
            T.ActivityID AS Activity_ActivityID, 
            T.ActivityName AS Activity_ActivityName, 
            T.ActivityIcon AS Activity_ActivityIcon, 
            T.ActivityTypeID AS Activity_ActivityTypeID, 
            T.ActivityAddress AS Activity_ActivityAddress, 
            T.ActivityAddressX AS Activity_ActivityAddressX, 
            T.ActivityAddressY AS Activity_ActivityAddressY, 
            T.ActivityContent AS Activity_ActivityContent, 
            T.ActivityPrediNum AS Activity_ActivityPrediNum, 
            T.ActivityManagerID AS Activity_ActivityManagerID, 
            T.ActivityApplyUserInfoID AS Activity_ActivityApplyUserInfoID, 
            T.ActivityApplyOrganizeID AS Activity_ActivityApplyOrganizeID, 
            T.ActivityClicks AS Activity_ActivityClicks, 
            T.ActivityEnrollEnd AS Activity_ActivityEnrollEnd, 
            T.ActivityEnrollStart AS Activity_ActivityEnrollStart, 
            T.ActivityStart AS Activity_ActivityStart, 
            T.ActivityEnd AS Activity_ActivityEnd, 
            T.ActivityPolitical AS Activity_ActivityPolitical, 
            T.ActivityMajor AS Activity_ActivityMajor, 
            T.ActivityDepartment AS Activity_ActivityDepartment, 
            T.CreateTime AS Activity_CreateTime, 
            T.ModfiedOn AS Activity_ModfiedOn, 
            T.Remark AS Activity_Remark, 
            T.Status AS Activity_Status, 
            T.ActivityAddressDetail AS Activity_ActivityAddressDetail, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Activity AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.ActivityDetail.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ActivityDetail
        [OjVolunteerModel.ActivityDetail](T1.ActivityDetail_ActivityDetailID, T1.ActivityDetail_UserInfoId, T1.ActivityDetail_ActivityID, T1.ActivityDetail_ActivityDetailTime, T1.ActivityDetail_CreateTime, T1.ActivityDetail_ModfiedOn, T1.ActivityDetail_Remark, T1.ActivityDetail_Status)
    FROM (
        SELECT 
            T.ActivityDetailID AS ActivityDetail_ActivityDetailID, 
            T.UserInfoId AS ActivityDetail_UserInfoId, 
            T.ActivityID AS ActivityDetail_ActivityID, 
            T.ActivityDetailTime AS ActivityDetail_ActivityDetailTime, 
            T.CreateTime AS ActivityDetail_CreateTime, 
            T.ModfiedOn AS ActivityDetail_ModfiedOn, 
            T.Remark AS ActivityDetail_Remark, 
            T.Status AS ActivityDetail_Status, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.ActivityDetail AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.ActivityType.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ActivityType
        [OjVolunteerModel.ActivityType](T1.ActivityType_ActivityTypeID, T1.ActivityType_ActivityTypeName, T1.ActivityType_CreateTime, T1.ActivityType_ModfiedOn, T1.ActivityType_Remark, T1.ActivityType_Status)
    FROM (
        SELECT 
            T.ActivityTypeID AS ActivityType_ActivityTypeID, 
            T.ActivityTypeName AS ActivityType_ActivityTypeName, 
            T.CreateTime AS ActivityType_CreateTime, 
            T.ModfiedOn AS ActivityType_ModfiedOn, 
            T.Remark AS ActivityType_Remark, 
            T.Status AS ActivityType_Status, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.ActivityType AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Favors.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Favors
        [OjVolunteerModel.Favors](T1.Favors_FavorID, T1.Favors_TalkID, T1.Favors_UserInfoID, T1.Favors_CreateTime, T1.Favors_ModfiedOn, T1.Favors_Remark, T1.Favors_Status)
    FROM (
        SELECT 
            T.FavorID AS Favors_FavorID, 
            T.TalkID AS Favors_TalkID, 
            T.UserInfoID AS Favors_UserInfoID, 
            T.CreateTime AS Favors_CreateTime, 
            T.ModfiedOn AS Favors_ModfiedOn, 
            T.Remark AS Favors_Remark, 
            T.Status AS Favors_Status, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Favors AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Integrals.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Integrals
        [OjVolunteerModel.Integrals](T1.Integrals_IntegralID, T1.Integrals_UserInfoID, T1.Integrals_IntegralNum, T1.Integrals_IntegralIndex, T1.Integrals_CreateTime, T1.Integrals_ModfiedOn, T1.Integrals_Remark, T1.Integrals_Status)
    FROM (
        SELECT 
            T.IntegralID AS Integrals_IntegralID, 
            T.UserInfoID AS Integrals_UserInfoID, 
            T.IntegralNum AS Integrals_IntegralNum, 
            T.IntegralIndex AS Integrals_IntegralIndex, 
            T.CreateTime AS Integrals_CreateTime, 
            T.ModfiedOn AS Integrals_ModfiedOn, 
            T.Remark AS Integrals_Remark, 
            T.Status AS Integrals_Status, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Integrals AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.OrganizeInfo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrganizeInfo
        [OjVolunteerModel.OrganizeInfo](T1.OrganizeInfo_OrganizeInfoID, T1.OrganizeInfo_OrganizeInfoShowName, T1.OrganizeInfo_OrganizeInfoPwd, T1.OrganizeInfo_OrganizeInfoPeople, T1.OrganizeInfo_OrganizeInfoPhone, T1.OrganizeInfo_OrganizeInfoEmail, T1.OrganizeInfo_OrganizeInfoManageId, T1.OrganizeInfo_OrganizeInfoLastTime, T1.OrganizeInfo_CreateTime, T1.OrganizeInfo_ModfiedOn, T1.OrganizeInfo_Remark, T1.OrganizeInfo_Status, T1.OrganizeInfo_OrganizeInfoIcon, T1.OrganizeInfo_OrganizeInfoLoginId, T1.OrganizeInfo_ActivityCount)
    FROM (
        SELECT 
            T.OrganizeInfoID AS OrganizeInfo_OrganizeInfoID, 
            T.OrganizeInfoShowName AS OrganizeInfo_OrganizeInfoShowName, 
            T.OrganizeInfoPwd AS OrganizeInfo_OrganizeInfoPwd, 
            T.OrganizeInfoPeople AS OrganizeInfo_OrganizeInfoPeople, 
            T.OrganizeInfoPhone AS OrganizeInfo_OrganizeInfoPhone, 
            T.OrganizeInfoEmail AS OrganizeInfo_OrganizeInfoEmail, 
            T.OrganizeInfoManageId AS OrganizeInfo_OrganizeInfoManageId, 
            T.OrganizeInfoLastTime AS OrganizeInfo_OrganizeInfoLastTime, 
            T.CreateTime AS OrganizeInfo_CreateTime, 
            T.ModfiedOn AS OrganizeInfo_ModfiedOn, 
            T.Remark AS OrganizeInfo_Remark, 
            T.Status AS OrganizeInfo_Status, 
            T.OrganizeInfoIcon AS OrganizeInfo_OrganizeInfoIcon, 
            T.OrganizeInfoLoginId AS OrganizeInfo_OrganizeInfoLoginId, 
            T.ActivityCount AS OrganizeInfo_ActivityCount, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.OrganizeInfo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Talks.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Talks
        [OjVolunteerModel.Talks](T1.Talks_TalkID, T1.Talks_UserInfoID, T1.Talks_TalkContent, T1.Talks_TalkFavorsNum, T1.Talks_CreateTime, T1.Talks_ModfiedOn, T1.Talks_Remark, T1.Talks_Status, T1.Talks_OrganizeInfoID, T1.Talks_TalkImagePath)
    FROM (
        SELECT 
            T.TalkID AS Talks_TalkID, 
            T.UserInfoID AS Talks_UserInfoID, 
            T.TalkContent AS Talks_TalkContent, 
            T.TalkFavorsNum AS Talks_TalkFavorsNum, 
            T.CreateTime AS Talks_CreateTime, 
            T.ModfiedOn AS Talks_ModfiedOn, 
            T.Remark AS Talks_Remark, 
            T.Status AS Talks_Status, 
            T.OrganizeInfoID AS Talks_OrganizeInfoID, 
            T.TalkImagePath AS Talks_TalkImagePath, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Talks AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.UserDuration.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserDuration
        [OjVolunteerModel.UserDuration](T1.UserDuration_UserDurationID, T1.UserDuration_UserDurationTotal, T1.UserDuration_UserDurationPropartyTotal, T1.UserDuration_UserDurationPartyTotal, T1.UserDuration_UserDurationPropartyTime, T1.UserDuration_UserDurationPartyTime, T1.UserDuration_CreateTime, T1.UserDuration_ModfiedOn, T1.UserDuration_Remark, T1.UserDuration_Status, T1.UserDuration_UserDurationNormalTotal)
    FROM (
        SELECT 
            T.UserDurationID AS UserDuration_UserDurationID, 
            T.UserDurationTotal AS UserDuration_UserDurationTotal, 
            T.UserDurationPropartyTotal AS UserDuration_UserDurationPropartyTotal, 
            T.UserDurationPartyTotal AS UserDuration_UserDurationPartyTotal, 
            T.UserDurationPropartyTime AS UserDuration_UserDurationPropartyTime, 
            T.UserDurationPartyTime AS UserDuration_UserDurationPartyTime, 
            T.CreateTime AS UserDuration_CreateTime, 
            T.ModfiedOn AS UserDuration_ModfiedOn, 
            T.Remark AS UserDuration_Remark, 
            T.Status AS UserDuration_Status, 
            T.UserDurationNormalTotal AS UserDuration_UserDurationNormalTotal, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.UserDuration AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.UserEnroll.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserEnroll
        [OjVolunteerModel.UserEnroll](T1.UserEnroll_UserEnrollID, T1.UserEnroll_ActivityID, T1.UserEnroll_UserInfoID, T1.UserEnroll_UserEnrollStart, T1.UserEnroll_UserEnrollActivityStart, T1.UserEnroll_UserEnrollActivityEnd, T1.UserEnroll_CreateTime, T1.UserEnroll_ModfiedOn, T1.UserEnroll_Remark, T1.UserEnroll_Status, T1.UserEnroll_ActivityTime)
    FROM (
        SELECT 
            T.UserEnrollID AS UserEnroll_UserEnrollID, 
            T.ActivityID AS UserEnroll_ActivityID, 
            T.UserInfoID AS UserEnroll_UserInfoID, 
            T.UserEnrollStart AS UserEnroll_UserEnrollStart, 
            T.UserEnrollActivityStart AS UserEnroll_UserEnrollActivityStart, 
            T.UserEnrollActivityEnd AS UserEnroll_UserEnrollActivityEnd, 
            T.CreateTime AS UserEnroll_CreateTime, 
            T.ModfiedOn AS UserEnroll_ModfiedOn, 
            T.Remark AS UserEnroll_Remark, 
            T.Status AS UserEnroll_Status, 
            T.ActivityTime AS UserEnroll_ActivityTime, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.UserEnroll AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.UserInfo.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserInfo
        [OjVolunteerModel.UserInfo](T1.UserInfo_UserInfoID, T1.UserInfo_UserInfoLoginId, T1.UserInfo_UserInfoPwd, T1.UserInfo_UserInfoStuId, T1.UserInfo_UserInfoShowName, T1.UserInfo_UserInfoPhone, T1.UserInfo_UserInfoEmail, T1.UserInfo_MajorID, T1.UserInfo_DepartmentID, T1.UserInfo_PoliticalID, T1.UserInfo_UserInfoLastTime, T1.UserInfo_CreateTime, T1.UserInfo_ModfiedOn, T1.UserInfo_Remark, T1.UserInfo_Status, T1.UserInfo_UpdatePoliticalID, T1.UserInfo_UserInfoIcon, T1.UserInfo_UserInfoIDcard, T1.UserInfo_UserInfoTalkCount, T1.UserInfo_OrganizeInfoID)
    FROM (
        SELECT 
            T.UserInfoID AS UserInfo_UserInfoID, 
            T.UserInfoLoginId AS UserInfo_UserInfoLoginId, 
            T.UserInfoPwd AS UserInfo_UserInfoPwd, 
            T.UserInfoStuId AS UserInfo_UserInfoStuId, 
            T.UserInfoShowName AS UserInfo_UserInfoShowName, 
            T.UserInfoPhone AS UserInfo_UserInfoPhone, 
            T.UserInfoEmail AS UserInfo_UserInfoEmail, 
            T.MajorID AS UserInfo_MajorID, 
            T.DepartmentID AS UserInfo_DepartmentID, 
            T.PoliticalID AS UserInfo_PoliticalID, 
            T.UserInfoLastTime AS UserInfo_UserInfoLastTime, 
            T.CreateTime AS UserInfo_CreateTime, 
            T.ModfiedOn AS UserInfo_ModfiedOn, 
            T.Remark AS UserInfo_Remark, 
            T.Status AS UserInfo_Status, 
            T.UpdatePoliticalID AS UserInfo_UpdatePoliticalID, 
            T.UserInfoIcon AS UserInfo_UserInfoIcon, 
            T.UserInfoIDcard AS UserInfo_UserInfoIDcard, 
            T.UserInfoTalkCount AS UserInfo_UserInfoTalkCount, 
            T.OrganizeInfoID AS UserInfo_OrganizeInfoID, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.UserInfo AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Badge.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Badge
        [OjVolunteerModel.Badge](T1.Badge_BadgeID, T1.Badge_BadgeName, T1.Badge_Staus, T1.Badge_Remark, T1.Badge_CreateTime, T1.Badge_ImgSrc)
    FROM (
        SELECT 
            T.BadgeID AS Badge_BadgeID, 
            T.BadgeName AS Badge_BadgeName, 
            T.Staus AS Badge_Staus, 
            T.Remark AS Badge_Remark, 
            T.CreateTime AS Badge_CreateTime, 
            T.ImgSrc AS Badge_ImgSrc, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Badge AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.UserBadge.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserBadge
        [OjVolunteerModel.UserBadge](T1.UserBadge_UserBadgeID, T1.UserBadge_UserInfoID, T1.UserBadge_BadgeID, T1.UserBadge_CreateTime, T1.UserBadge_Staus)
    FROM (
        SELECT 
            T.UserBadgeID AS UserBadge_UserBadgeID, 
            T.UserInfoID AS UserBadge_UserInfoID, 
            T.BadgeID AS UserBadge_BadgeID, 
            T.CreateTime AS UserBadge_CreateTime, 
            T.Staus AS UserBadge_Staus, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.UserBadge AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Department.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Department
        [OjVolunteerModel.Store.Department](T1.Department_DepartmentID, T1.Department_DepartmentName, T1.Department_CreateTime, T1.Department_ModfiedOn, T1.Department_Remark, T1.Department_Status)
    FROM (
        SELECT 
            T.DepartmentID AS Department_DepartmentID, 
            T.DepartmentName AS Department_DepartmentName, 
            T.CreateTime AS Department_CreateTime, 
            T.ModfiedOn AS Department_ModfiedOn, 
            T.Remark AS Department_Remark, 
            T.Status AS Department_Status, 
            True AS _from0
        FROM OjVolunteerEntities.Department AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Department.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Department
        [OjVolunteerModel.Department](T1.Department_CreateTime, T1.Department_ModfiedOn, T1.Department_Remark, T1.Department_Status, T1.Department_DepartmentID, T1.Department_DepartmentName)
    FROM (
        SELECT 
            T.CreateTime AS Department_CreateTime, 
            T.ModfiedOn AS Department_ModfiedOn, 
            T.Remark AS Department_Remark, 
            T.Status AS Department_Status, 
            T.DepartmentID AS Department_DepartmentID, 
            T.DepartmentName AS Department_DepartmentName, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Department AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Major.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Major
        [OjVolunteerModel.Store.Major](T1.Major_MajorID, T1.Major_MajorName, T1.Major_CreateTime, T1.Major_ModfiedOn, T1.Major_Remark, T1.Major_Status)
    FROM (
        SELECT 
            T.MajorID AS Major_MajorID, 
            T.MajorName AS Major_MajorName, 
            T.CreateTime AS Major_CreateTime, 
            T.ModfiedOn AS Major_ModfiedOn, 
            T.Remark AS Major_Remark, 
            T.Status AS Major_Status, 
            True AS _from0
        FROM OjVolunteerEntities.Major AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Major.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Major
        [OjVolunteerModel.Major](T1.Major_MajorID, T1.Major_MajorName, T1.Major_CreateTime, T1.Major_ModfiedOn, T1.Major_Remark, T1.Major_Status)
    FROM (
        SELECT 
            T.MajorID AS Major_MajorID, 
            T.MajorName AS Major_MajorName, 
            T.CreateTime AS Major_CreateTime, 
            T.ModfiedOn AS Major_ModfiedOn, 
            T.Remark AS Major_Remark, 
            T.Status AS Major_Status, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Major AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.Political.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Political
        [OjVolunteerModel.Store.Political](T1.Political_PoliticalID, T1.Political_PoliticalName, T1.Political_CreateTime, T1.Political_ModfiedOn, T1.Political_Remark, T1.Political_Status)
    FROM (
        SELECT 
            T.PoliticalID AS Political_PoliticalID, 
            T.PoliticalName AS Political_PoliticalName, 
            T.CreateTime AS Political_CreateTime, 
            T.ModfiedOn AS Political_ModfiedOn, 
            T.Remark AS Political_Remark, 
            T.Status AS Political_Status, 
            True AS _from0
        FROM OjVolunteerEntities.Political AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.Political.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView29()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Political
        [OjVolunteerModel.Political](T1.Political_PoliticalID, T1.Political_PoliticalName, T1.Political_CreateTime, T1.Political_ModfiedOn, T1.Political_Remark, T1.Political_Status)
    FROM (
        SELECT 
            T.PoliticalID AS Political_PoliticalID, 
            T.PoliticalName AS Political_PoliticalName, 
            T.CreateTime AS Political_CreateTime, 
            T.ModfiedOn AS Political_ModfiedOn, 
            T.Remark AS Political_Remark, 
            T.Status AS Political_Status, 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.Political AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerModelStoreContainer.v_User_ActDetail.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView30()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing v_User_ActDetail
        [OjVolunteerModel.Store.v_User_ActDetail](T1.[v_User_ActDetail.ActivityDetailID], T1.[v_User_ActDetail.UserInfoId], T1.[v_User_ActDetail.ActivityDetailTime], T1.[v_User_ActDetail.CreateTime], T1.[v_User_ActDetail.OrganizeInfoID])
    FROM (
        SELECT 
            T.ActivityDetailID AS [v_User_ActDetail.ActivityDetailID], 
            T.UserInfoId AS [v_User_ActDetail.UserInfoId], 
            T.ActivityDetailTime AS [v_User_ActDetail.ActivityDetailTime], 
            T.CreateTime AS [v_User_ActDetail.CreateTime], 
            T.OrganizeInfoID AS [v_User_ActDetail.OrganizeInfoID], 
            True AS _from0
        FROM OjVolunteerEntities.v_User_ActDetail AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for OjVolunteerEntities.v_User_ActDetail.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView31()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing v_User_ActDetail
        [OjVolunteerModel.v_User_ActDetail](T1.[v_User_ActDetail.ActivityDetailID], T1.[v_User_ActDetail.UserInfoId], T1.[v_User_ActDetail.ActivityDetailTime], T1.[v_User_ActDetail.CreateTime], T1.[v_User_ActDetail.OrganizeInfoID])
    FROM (
        SELECT 
            T.ActivityDetailID AS [v_User_ActDetail.ActivityDetailID], 
            T.UserInfoId AS [v_User_ActDetail.UserInfoId], 
            T.ActivityDetailTime AS [v_User_ActDetail.ActivityDetailTime], 
            T.CreateTime AS [v_User_ActDetail.CreateTime], 
            T.OrganizeInfoID AS [v_User_ActDetail.OrganizeInfoID], 
            True AS _from0
        FROM OjVolunteerModelStoreContainer.v_User_ActDetail AS T
    ) AS T1");
        }
    }
}
