
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace OjVolunteer.Model
{


using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class UserIDcard
{

    public int IDcardId { get; set; }

    public int IDcardOwnerId { get; set; }

    public int IDcardStatus { get; set; }

    public System.DateTime IDcardApplyTime { get; set; }



    public virtual UserInfo UserInfo { get; set; }

}

}
